MOUSEKEY_ENABLE     = yes     # Mouse keys
RGBLIGHT_ENABLE     = no    # Enable WS2812 RGB underlight.
VIA_ENABLE          = yes         # Enable VIA
VIAL_ENABLE         = yes         # Enable VIAL
OLED_DRIVER_ENABLE  = no
EXTRAKEY_ENABLE     = yes
LTO_ENABLE          = yes
QMK_SETTINGS        = yes
COMBO_ENABLE        = yes
